// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sdzvearktjsqtpwqdbfc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNkenZlYXJrdGpzcXRwd3FkYmZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4Nzc4OTcsImV4cCI6MjA2NDQ1Mzg5N30.oweWUFg_vntf8aSSNtjXbPSTECVtEu3b-_gP9qr6l3w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);